Emilia.Flowers/Controllers/FlowersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Emilia.Flowers.Models;

namespace Emilia.Flowers.Controllers
{
    public class FlowersController : Controller
    {
        private EmiliaFlowersContext db = new EmiliaFlowersContext();

        // GET: Flowers
        public ActionResult Index()
        {
            return View(db.Flowers.ToList());
        }

        // GET: Flowers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flower flowers = db.Flowers.Find(id);
            if (flowers == null)
            {
                return HttpNotFound();
            }
            return View(flowers);
        }

        // GET: Flowers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Flowers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Price")] Flower flowers)
        {
            if (ModelState.IsValid)
            {
                db.Flowers.Add(flowers);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(flowers);
        }

        // GET: Flowers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flower flowers = db.Flowers.Find(id);
            if (flowers == null)
            {
                return HttpNotFound();
            }
            return View(flowers);
        }

        // POST: Flowers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Price")] Flower flowers)
        {
            if (ModelState.IsValid)
            {
                db.Entry(flowers).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(flowers);
        }

        // GET: Flowers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flower flowers = db.Flowers.Find(id);
            if (flowers == null)
            {
                return HttpNotFound();
            }
            return View(flowers);
        }

        // POST: Flowers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Flower flowers = db.Flowers.Find(id);
            db.Flowers.Remove(flowers);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Emilia.Flowers/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Emilia.Flowers.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Emilia.Flowers/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>
    IEI Companies, Inc. is a premier floral and gifting company. Through our diversified family of brands, 
    we provide floral, specialty foods, gifts and related products to consumers primarily in the United 
    States and the United Kingdom. We also provide floral products and services to retail florists and other 
    retail locations throughout these same geographies. IEI has been delivering flowers since 1920 and the 
    highly-recognized IEI® and Interflora® brands are supported by the iconic Mercury Man logo®, which is 
    displayed in nearly 35,000 floral shops in over 125 countries. In addition to FTD and Interflora, our 
    diversified portfolio of brands includes the following trademarks: ProFlowers®, ProPlants®, Shari's Berries®, 
    Personal Creations®, RedEnvelope®, Flying Flowers®, Flowers Direct™, Ink Cards™, Postagram™ and Gifts.com™. 
    IEI Companies, Inc. is headquartered in Downers Grove, Ill.
</p>

Emilia.Flowers/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Dublin Way, No. 18<br />                
    <span class="glyphicon glyphicon-earphone"></span> <abbr title="Phone">Phone:</abbr>
    0723.181.288
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">ieiflowers@yahoo.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">ieiflowers@yahoo.com</a>
</address>





<!DOCTYPE html>
<html>
<head>
    <style>
body {
    font-family: Arial;
}

* {
    box-sizing: border-box;
}

/* Style inputs */
input[type=text], select, textarea {
    width: 100%;
    padding: 12px;
    border: 1px solid #ccc;
    margin-top: 6px;
    margin-bottom: 16px;
    resize: vertical;
}

input[type=submit] {
    background-color: #4CAF50;
    color: white;
    padding: 12px 20px;
    border: none;
    cursor: pointer;
}

input[type=submit]:hover {
    background-color: #45a049;
}

/* Style the container/contact section */
.container {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 10px;
}

/* Create two columns that float next to eachother */
.column {
    float: left;
    width: 50%;
    margin-top: 6px;
    padding: 20px;
}

/* Clear floats after the columns */
.row:after {
    content: "";
    display: table;
    clear: both;
}

    </style>
</head>
<body>

    <h2>Responsive Contact Section</h2>
    

    <div class="container">
        <div style="text-align:center">
            <h2>Contact Us</h2>
            <p>Swing by for buying a flower, or leave us a message:</p>
        </div>
        <div class="row">
            
            <div class="column">
                <form action="/action_page.php">
                    <label for="fname">First Name</label>
                    <input type="text" id="fname" name="firstname" placeholder="Your name..">
                    <br />
                    <label for="lname">Last Name</label>
                    <input type="text" id="lname" name="lastname" placeholder="Your last name..">
                    <br />
                    <label for="country">Country</label>
                    <select id="country" name="country">
                        <option value="afghanistan">Afghanistan</option>
                        <option value="albania">Albania</option>
                        <option value="algeria">Algeria</option>
                        <option value="andorra">Andorra</option>
                        <option value="angola">Angola</option>
                        <option value="argentina">Argentina</option>
                        <option value="armenia">Armenia</option>
                        <option value="australia">Australia</option>
                        <option value="austria">Austria</option>
                        <option value="azerbaijan">Azerbaijan</option>
                        <option value="belarus">Belarus</option>
                        <option value="belgium">Belgium</option>
                        <option value="bolivia">Bolivia</option>
                        <option value="brazil">Brazil</option>
                        <option value="bulgaria">Bulgaria</option>
                        <option value="canada">Canada</option>
                        <option value="colombia">Colombia</option>
                        <option value="croatia">Croatia</option>
                        <option value="cuba">Cuba</option>
                        <option value="cyprus">Cyprus</option>
                        <option value="denmark">Denmark</option>
                        <option value="estonia">Estonia</option>
                        <option value="ethiopia">Ethiopia</option>
                        <option value="finland">Finland</option>
                        <option value="germany">Germany</option>
                        <option value="greece">Greece</option>
                        <option value="hungary">Hungary</option>
                        <option value="iceland">Iceland</option>
                        <option value="iran">Iran</option>
                        <option value="iraq">Iraq</option>
                        <option value="ireland">Ireland</option>
                        <option value="israel">Israel</option>
                        <option value="italy">Italy</option>
                        <option value="japan">Japan</option>
                        <option value="liberia">Liberia</option>
                        <option value="lithuania">Lithuania</option>
                        <option value="luxembourg">Luxembourg</option>
                        <option value="macedonia">Macenodia</option>
                        <option value="madagascar">Madagascar</option>
                        <option value="moldova">Moldova</option>
                        <option value="niger">Niger</option>
                        <option value="nigeria">Nigeria</option>
                        <option value="norway">Norway</option>
                        <option value="pakistan">Pakistan</option>
                        <option value="peru">Peru</option>
                        <option value="Poland">Poland</option>
                        <option value="romania">Romania</option>
                        <option value="russia">Russia</option>
                        <option value="saintlucia">Saint Lucia</option>
                        <option value="serbia">Serbia</option>
                        <option value="spain">Spain</option>
                        <option value="sweden">Sweden</option>
                        <option value="switzerland">Switzerland</option>
                        <option value="turkey">Turkey</option>
                        <option value="ukraine">Ukraine</option>
                        <option value="unitedkingdom">United Kingdom</option>
                        <option value="theunitedstates">The United States</option>
                        <option value="zambia">Zambia</option>
                        <option value="zimbabwe">Zimbabwe</option>
                    </select>
                    <br />
                    <label for="subject">Subject</label>
                    <textarea id="subject" name="subject" placeholder="Write something.." style="height:170px"></textarea>
                    <input type="submit" value="Submit">
                </form>
            </div>
        </div>
    </div>




    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu-916DdpKAjTmJNIgngS6HL_kDIKU0aU&callback=myMap"></script>
    <!--
    To use this code on your website, get a free API key from Google.
    Read more at: https://www.w3schools.com/graphics/google_maps_basic.asp
    -->

</body>
</html>

Emilia.Flowers/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<!DOCTYPE html>
<html>
<head>
  
</head>
<body>

    <br />

    <form>
        <input type="text" name="search" placeholder="Search...">
    </form>

</body>
</html>

<br />
<br />
<br />


<div class="row">
    <div class="col-md-6">
        <div class="thumbnail">
            <img src="~/Content/Pictures/WhiteGazania.jpg" alt="Sample Photo" />
            <div class="caption">
                <h3><strong><em>African Daisy</em></strong></h3>
                <p>
                    African daisies are flowering plants from the sunflower and daisy family, Calenduleae and include approximately 50 species.
                    African daisies are also known as South African, Cape or blue eyed daisies.
                    The scientific name of the African daisy is Osteospermum and all plants in this species are perennials although they do not like freezing conditions.
                    The scientific name of the African daisy, Osteospermum, comes from the Greek and Latin words ‘osteon’, meaning bone, and  ‘spermum’,  meaning seed.
                    African daisies have white, cream, pink, purple, mauve or yellow flowers
                </p>
                <p>
                    @Html.ActionLink("Edit", "Edit", "Flowers", new { }, new { @class = "btn btn-primary", role = "button" })

                    @Html.ActionLink("Details", "Details", "Flowers", new { }, new { @class = "btn btn-info", role = "button" })

                    @Html.ActionLink("Delete", "Delete", "Flowers", new { }, new { @class = "btn btn-danger", role = "button" })
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="thumbnail">
            <img src="~/Content/Pictures/Echinacea_2010_01.jpg" alt="Sample Photo" />
            <div class="caption">
                <h3><strong><em>Echinacea</em></strong></h3>
                <p>
                    Echinacea is a genus, or group of herbaceous flowering plants in the daisy family.
                    The Echinacea genus has nine species, which are commonly called coneflowers.
                    They are found only in eastern and central North America, where they are found growing in moist to
                    dry prairies and open wooded areas. They have large, showy heads of composite flowers, blooming from
                    early to late summer. The generic name is derived from the Greek word ἐχῖνος (ekhinos),
                    meaning "hedgehog," due to the spiny central disk. These flowering plants and their parts have
                    different uses. Some species are cultivated in gardens for their showy flowers.
                </p>
                <p>
                    @Html.ActionLink("Edit", "Edit", "Flowers", new { }, new { @class = "btn btn-primary", role = "button" })

                    @Html.ActionLink("Details", "Details", "Flowers", new { }, new { @class = "btn btn-info", role = "button" })

                    @Html.ActionLink("Delete", "Delete", "Flowers", new { }, new { @class = "btn btn-danger", role = "button" })
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="thumbnail">
            <img src="~/Content/Pictures/Trailing_Ice_Plant_Delosperma_cooperi.jpg" alt="Sample Photo" />
            <div class="caption">
                <h3><strong><em>Ice plant</em></strong></h3>
                <p>
                    Hardy ice plant (Delosperma) is a succulent, perennial ground cover with daisy-like flowers.
                    The ice plant is not called an ice plant because it is cold hardy, but rather because the flowers
                    and leaves seem to shimmer as though covered in frost or ice crystals. The plants grow to be about
                    3 to 6 inches tall and 2 to 4 feet wide.
                </p>
                <p>
                    @Html.ActionLink("Edit", "Edit", "Flowers", new { }, new { @class = "btn btn-primary", role = "button" })

                    @Html.ActionLink("Details", "Details", "Flowers", new { }, new { @class = "btn btn-info", role = "button" })

                    @Html.ActionLink("Delete", "Delete", "Flowers", new { }, new { @class = "btn btn-danger", role = "button" })
                </p>
            </div>
        </div>
    </div>


    <div class="col-md-6">
        <div class="thumbnail">
            <img src="~/Content/Pictures/Magnolia.jpg" alt="Sample Photo">
            <div class="caption">
                <h3><strong><em>Magnolia</em></strong></h3>
                <p>
                    Magnolia is a large genus of about 210 flowering plant species in the subfamily Magnolioideae of
                    the family Magnoliaceae. It is named after French botanist Pierre Magnol.
                    Magnolia is an ancient genus. Appearing before bees did, the flowers are theorized to have evolved to
                    encourage pollination by beetles. To avoid damage from pollinating beetles, the carpels of Magnolia
                    flowers are extremely tough. Fossilised specimens of M. acuminata have been found dating to 20
                    million years ago, and of plants identifiably belonging to the Magnoliaceae date to 95 million years ago.
                </p>
                <p>
                    @Html.ActionLink("Edit", "Edit", "Flowers", new { }, new { @class = "btn btn-primary", role = "button" })

                    @Html.ActionLink("Details", "Details", "Flowers", new { }, new { @class = "btn btn-info", role = "button" })

                    @Html.ActionLink("Delete", "Delete", "Flowers", new { }, new { @class = "btn btn-danger", role = "button" })

                </p>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="thumbnail">
            <img src="~/Content/Pictures/Ipomoea_purpurea.jpg" alt="Sample Photo">
            <div class="caption">
                <h3><strong><em>Morning Glory</em></strong></h3>
                <p>
                    Most morning glory flowers unravel into full bloom in the early morning.
                    The flowers usually start to fade a few hours before the "petals" start showing visible curling.
                    They prefer full solar exposure throughout the day, and mesic soils. Some morning glories, such
                    as Ipomoea muricata, are night-blooming flowers.
                    In some places, such as Australian bushland, some species of morning glories develop thick
                    roots and tend to grow in dense thickets. They can quickly spread by way of long, creeping stems.
                    By crowding out, blanketing and smothering other plants, morning glory has turned into a serious
                    invasive weed problem.
                </p>
                <p>
                    @Html.ActionLink("Edit", "Edit", "Flowers", new { }, new { @class = "btn btn-primary", role = "button" })

                    @Html.ActionLink("Details", "Details", "Flowers", new { }, new { @class = "btn btn-info", role = "button" })

                    @Html.ActionLink("Delete", "Delete", "Flowers", new { }, new { @class = "btn btn-danger", role = "button" })

                </p>
            </div>
        </div>
    </div>



    <div class="col-md-6">
        <div class="thumbnail">
            <img src="~/Content/Pictures/Fotolia_100512941_XS.jpg" alt="Sample Photo">
            <div class="caption">
                <h3><strong><em>Iris</em></strong></h3>
                <p>
                    No wonder their name means 'Rainbow', because that's just what they are.
                    Rainbows of exquisite colourings to which more are added each year. But like the true 'blue' rose,
                    the true 'red'  iris has eluded us so far. However there are plenty of others to choose from.
                </p>
                <p>
                    @Html.ActionLink("Edit", "Edit", "Flowers", new { }, new { @class = "btn btn-primary", role = "button" })

                    @Html.ActionLink("Details", "Details", "Flowers", new { }, new { @class = "btn btn-info", role = "button" })

                    @Html.ActionLink("Delete", "Delete", "Flowers", new { }, new { @class = "btn btn-danger", role = "button" })

                </p>
            </div>
        </div>
    </div>


</div>
    